apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  namespace: gacas
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: eu.gcr.io/dev-production/hello-world-gacas:v1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
          ports:
            - containerPort: 8080
          # Readness Probe
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          # Liveness Probe
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
